### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S

### ISSUE THREAD

**Issue by CedzyC** [webchain-network/webchain-wallet#128] opened 2019-06-30 11:28 UTC
``` 
JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Cedrik/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///C:/Users/Cedrik/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
    at file:///C:/Users/Cedrik/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
 ```

**Comment by danielwebimp** [comment] 2019-07-17 11:01
> ```
> JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).S
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Cedrik/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
>     at new JsonRpcError (file:///C:/Users/Cedrik/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
>     at file:///C:/Users/Cedrik/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
> ```

Hi, please can you explain how to reproduce this error? If possible, could you try to reproduce it with new wallet release? Specify also the operating system.

**Comment by CedzyC** [comment] 2019-07-17 14:04
I was about to send web to a other address. But I didn't get the error since the new version of the wallet.

**Comment by danielwebimp** [comment] 2019-07-20 13:41
Ok thanks. Then I think this issue can closed because it has been fixed in the latest release.

**Closed by danielwebimp** 2019-07-20 13:41 UTC
